#!/bin/bash
###################################
# Name of the job
#SBATCH --job-name=ZLM_mix
#SBATCH --account=zhigang.li
#SBATCH --qos=zhigang.li
###################################
# Number of compute nodes
#SBATCH --nodes=1
###################################
# Number of cores
#SBATCH --ntasks-per-node=1
###################################
# Array jobs
#SBATCH --array=1-100
###################################
# Walltime (job duration)
#SBATCH --time=90:15:00
###################################
###################################

module load R

RUN=${SLURM_ARRAY_TASK_ID:-1}

Rscript add_conf_code.R ${RUN} ${RUN} > ZLM_mix_${RUN}.out

date
